﻿// <auto-generated />
/// <summary>
/// Auto-generated designer file for the initial migration.
/// </summary>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sprint2.Data;

#nullable disable

namespace Sprint2.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250225185556_InitialCreate")]
/// <summary>
/// Represents the initial migration for creating the Tasks table.
/// </summary>
partial class InitialCreate
    {
        /// <inheritdoc />
/// <summary>
/// Configures the target model for the migration using the ModelBuilder.
/// </summary>
/// <param name="modelBuilder">The ModelBuilder used to configure the model.</param>
protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
modelBuilder
    // Configures the model annotations and properties
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

modelBuilder.Entity("Sprint2.Models.TodoTask", b =>
    // Configures the TodoTask entity properties and constraints
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tasks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
